### ISSUE TITLE
[Suggestion] - a short description/title

### ISSUE THREAD

**Issue by TecoChN** [eingruenesbeb/Yolo#1]
Sry, wollte nur fragen ob es möglich wäre auch totem usages damit anzeigen zu lassen weil ein totem use auch ein tod ist 
MfG Teco C[h] N

**Comment by TecoChN** [comment]
Habs jetzt zum richtigen bearbeiten, hab davor ausversehen enter gedrückt

**Comment by eingruenesbeb** [comment]
Please keep everything in english here and use the template correctly.

**Comment by TecoChN** [comment]
> Please keep everything in english here and use the template correctly.

Ok i will sowwy, I did it to fast, my bad. Will rewrite it again. As mentioned earlier I send it to early before i could read anything. I will delete it in 1 min or so if i can

**Comment by TecoChN** [comment]
I cant delete it. Can u please delete it if possible or will it be here for ever to have something to make fun? 
Teco C[h] N
