### ISSUE TITLE
[Suggestion] - Custom Death Message Color 

### ISSUE THREAD

**Issue by AWobbuffet** [eingruenesbeb/Yolo#13]
**Is your feature request related to a problem? Please describe.**
Not related to a problem but moreso just a somewhat QoL change if you could call it that.

**Describe the solution you'd like**
I want to know if there's a way where you can change the color of the vanilla death messages that show for this, like if that's something that's possible since you already had an area for just a custom death message in general. What I want is like a way to have the normal messages that you'd see in vanilla minecraft be the same but also a way to customize the color for those death messages in a way to make them pop out more so like make them red and bold or something like that (I'll post images below of what I mean)

**Describe alternatives you've considered**
I tried to use another plugin that changed death messages however it was very buggy and in the end didn't work as you had to individually edit every single message then I realized it didn't work with deathban because the death message is delayed and happens after the player has already left the game and been considered deathbanned.

**Additional context**
 I will put screenshots below of an example of what it looks like normally and what I want to be able to change 

![Screenshot 2023-04-21 235509](https://user-images.githubusercontent.com/128919068/233763449-f4e2c598-d9b5-44cb-a8a8-100b48aafe5b.png)
![ss2](https://user-images.githubusercontent.com/128919068/233763454-47ca5fc3-4afc-472a-bbe4-87b4b1671ab1.png)
![ss3](https://user-images.githubusercontent.com/128919068/233763457-a3b98dab-1b48-4a21-8837-b2a7d82592a6.png)

**Comment by eingruenesbeb** [comment]
I wouldn't add this functionality directly, as I believe that to be just a bit out of scope of this plugin. However, the next version 0.7.0 will be able to support a placeholder `%death_message%` for death-messages. Therefore, you could then edit it (as a whole) in the message, that gets sent upon a player being death-banned.

If you're looking for a Plugin, that customizes the chat messages directly, I'd suggest you, to take a look at [ChatManager](https://modrinth.com/plugin/chatmanager).

**Comment by AWobbuffet** [comment]
Thank you for responding however I do have a question, I was looking at the ChatManger plugin and there doesn't seem to be an area for death messages. Are you just talking about normal chat messages like leaving and joining the game or the actual death message, and if yes where is the config area for death messages cause I can't find it. Thanks again!

**Comment by eingruenesbeb** [comment]
I'm sorry. I guess the plugin I've suggested, doesn't actually seem to provide this functionality. However, I'm certain, that there is probably another one out there, that suits your needs in terms of a chat overhaul. 

As stated previously, I'd consider this to be out of scope for Yolo. But thinking about it, an option to suppress the death message, upon a death-ban occurring, could be considered. (It's a bit janky of a solution though...)

**Comment by eingruenesbeb** [comment]
Oh... another mistake on my end. I think, I misunderstood something. 

Let me get this right: You've tried to use such a plugin, but a compatibility issue occurred, due to the player being banned, before the death-message is being sent. I suppose, the text showing up in red, indicates an error and is unintentional.
**Correct me, if I'm wrong here.**

This arises due to how the plugin operates. This should be an easy fix. I'll include that in the next update.

**Comment by AWobbuffet** [comment]
The issue here is that I WANT the text to show up in red. I use a plugin that changes death messages however due to how your plugin works the death message is normally delayed for the other plugin since it's using a custom tellraw. This means that since the player is banned INSTANTLY as they die there is no time for the custom death message plugin to actually show the custom death message if that makes sense. If not please explain to me where the confusion occurs and I will try to explain to my best ability.

**Comment by eingruenesbeb** [comment]
I see... 
I could delay the ban by a bit, but this shouldn't actually be necessary, as Plugins could simply manipulate the message directly. If it's about showing the message to the dead player, there will be a placeholder for that in the next update,

What plugin are you using to change the messages?

**Comment by AWobbuffet** [comment]
https://www.spigotmc.org/resources/deathmessages.3789/

**Comment by eingruenesbeb** [comment]
Fixed in [0.7.0](https://modrinth.com/plugin/yolo/version/0.7.0). The ban will now be deferred by one tick, which resolves this issue (and many other potential compatibility issues).
