### ISSUE TITLE
[Suggestion] - Totem trigger

### ISSUE THREAD

**Issue by TecoChN** [eingruenesbeb/Yolo#2]
Hello, 
I love the idea of Yolo but I would enjoy it even more if one more feature would be added. 
The thing with Minecraft is that there is a way around death, so called Totem of Undying as u probaly know.
Would it be possible to add a config where u can show Totems triggers as well?
Teco C[h] N

**Comment by eingruenesbeb** [comment]
You should still adhere to the template. Anyway...
What exactly do you mean by "show". There are several different options:
- Ingame-chat
- Console
- Via Spicord-integration
- Any combination of the three

**Comment by TecoChN** [comment]
Well if i understood Yolo til now correctly, then its there to inform other players and to ensure hardcore on multiplayer. With my suggestion I want to enhance the first part of Yolo and make it visible for other players. Therefore I would find it nice if it would be visible in Ingame and Spicord. 
Teco C[h] N

**Comment by eingruenesbeb** [comment]
@TecoChN I'm ready to test the new feature. If you want and don't mind, you can help with that. The attached file is the test-version (you have to unpack it).
[Yolo-0.5.0.zip](https://github.com/eingruenesbeb/Yolo/files/10951645/Yolo-0.5.0.zip)
