### ISSUE TITLE
I have 2 suggestions for this plugin.

### ISSUE THREAD

**Issue by AWobbuffet** [eingruenesbeb/Yolo#4]
My first suggestion is a way for this plugin to enable custom ban messages without using advanced ban. My reasoning for this is because when using advancedban the player dies THEN bans them as opposed to without it it bans the player before showing their death. I want it to ban the player before showing their death as that bans them a tick before their items are removed from their inventory as they drop on death. It makes it a LOT easier if you need to revive someone because you wouldn't have to replenish their items and go through the process of asking for screenshots of their inventory and such however I'm also not a fan of the original ban on death message because it isn't what I want to say when they die and I can't customize it. Please make this suggestion a reality as I really want to use this plugin for future events and such of mine.

My second suggestion is to add a way to disable and enable the deathban functionality of the plugin because I might not want players to be banned on the spot but I also wouldn't want to have to straight up remove the plugin for that and then restart the server to reinstall that as that's a bit annoying for most players to have to wait for the server to restart and for me to config the plugin.

Other than this I think it's a really good plugin and I want to thank you for making this!

**Comment by AWobbuffet** [comment]
Sorry for not following the format completely😅. I didn't realize what it was before I had finished and sent my comment. My apologies!

**Comment by eingruenesbeb** [comment]
Hey, no worries, I won't reject issues, if they don't follow the template. It's just there to provide the one creating it a format to include every bit of info I need and for me to be able to extract that info faster and better. It should also be noted, that separate suggestions should be in separate issues, but I digress... On to your suggestions:

- Easier method to revive a player: 
I'm currently working on a system, that allows for reviving players with their pre-death inventory and position (if it's safe). I guess that would solve your issues. If you're interested on the progress, you can take a look at the PR draft #5. For now, you can (somewhat jankily) restore the inventory using [CoreProtect](https://www.spigotmc.org/resources/coreprotect.8631/).
- Config option for toggling the death-ban functionality:
I don't quite understand, what exactly you mean here. This plugin's entire point is it's death-ban functionality. Could you elaborate on what exactly you've got in mind?

**Comment by AWobbuffet** [comment]
What I mean is a way to turn it on and off. I understand that plugin’s purpose is to ban people on death however I also thought it would be good for somethings if there was a way to toggle it off and on because while people use it for it’s only feature they also might want to have it off for a bit such as if they’re doing an event but don’t want it on right when it starts so players don’t automatically die and are gone right when the event starts. Also for the first thing my suggestion wasn’t exactly an easier way to revive a player it was more so a way to make custom ban messages without having to use advancedbans (because like I said before it doesn’t save the player’s inventory) but thank you for considering my suggestion!

**Comment by eingruenesbeb** [comment]
Ok, thanks for clearing that up. 
I guess both features shouldn't be hard to implement, so I'd include them in 0.6.0. 👍🏻

**Comment by AWobbuffet** [comment]
Okay thank you!

**Comment by eingruenesbeb** [comment]
Hey, I'm reopening this, to keep track of it until I push out the new version.

**Comment by eingruenesbeb** [comment]
I added the features in 0.6.0. I'll just have to add a new release now.
Feel free to make a new issue, if the features are not like you intended or if you would like to suggest more.
